# Generated by Django 4.1.6 on 2023-02-16 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_alter_member_proficiency'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='password',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='proficiency',
            field=models.CharField(choices=[('Beginner', '1'), ('Intermediate', '2'), ('Expert', '3')], default='Beginner', max_length=20),
        ),
    ]
