# Generated by Django 4.1.6 on 2023-02-16 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_member_address_member_age_member_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='contact',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
