# Generated by Django 4.1.6 on 2023-02-17 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_member_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='username',
            field=models.CharField(default='non', max_length=100),
        ),
        migrations.AlterField(
            model_name='member',
            name='password',
            field=models.CharField(default='non', max_length=12),
        ),
    ]
