# Generated by Django 4.1.6 on 2023-02-17 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_member_username_alter_member_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='password',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='member',
            name='username',
            field=models.CharField(max_length=100),
        ),
    ]
