# Generated by Django 4.1.6 on 2023-02-21 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0008_alter_member_password_alter_member_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='email',
            field=models.EmailField(default='xyz@email.com', max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='username',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
