# Generated by Django 4.1.6 on 2023-02-21 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0010_alter_member_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='proficiency',
            field=models.CharField(choices=[('1', 'Beginner'), ('2', 'Intermediate'), ('3', 'Expert')], default='1', max_length=20),
        ),
    ]
